# Generated by Django 6.0.4 on 2026-05-08 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('type', models.CharField(choices=[('Vacuna', 'Vacuna'), ('Revision', 'Revisión'), ('Cirugia', 'Cirugía'), ('Desparasitacion', 'Desparasitación'), ('Enfermedad', 'Enfermedad'), ('Otro', 'Otro')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_events', to='animales.animal')),
            ],
            options={
                'verbose_name': 'Medical Event',
                'verbose_name_plural': 'Medical Events',
                'ordering': ['-incident_date'],
            },
        ),
    ]
