# Generated by Django 6.0.1 on 2026-05-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_medicalevent_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalevent',
            old_name='type',
            new_name='event_type',
        ),
    ]
