# Generated by Django 6.0.4 on 2026-05-12 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_remove_animal_owners_delete_animalowner'),
        ('health', '0003_rename_type_medicalevent_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalevent',
            options={'ordering': ['-incident_date'], 'verbose_name': 'Evento Médico', 'verbose_name_plural': 'Eventos Médicos'},
        ),
        migrations.AlterField(
            model_name='medicalevent',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_events', to='animales.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='medicalevent',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='medicalevent',
            name='event_type',
            field=models.CharField(choices=[('Emergencia', 'Emergencia'), ('Consulta', 'Consulta'), ('Control', 'Control'), ('Procedimiento', 'Procedimiento')], max_length=30, verbose_name='Tipo de atención'),
        ),
        migrations.AlterField(
            model_name='medicalevent',
            name='incident_date',
            field=models.DateField(verbose_name='Fecha de la atención'),
        ),
    ]
