# Generated by Django 6.0.5 on 2026-05-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_medicalevent_options_alter_medicalevent_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalevent',
            name='event_type',
            field=models.CharField(choices=[('Emergencia', 'Emergencia'), ('Consulta', 'Consulta'), ('Control', 'Control'), ('Procedimiento', 'Procedimiento'), ('Otro', 'Otro')], max_length=30, verbose_name='Tipo de atención'),
        ),
    ]
