# Generated by Django 6.0.5 on 2026-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_medicalevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalevent',
            name='severity',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10, verbose_name='Severidad'),
        ),
        migrations.AddField(
            model_name='medicalevent',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('En Proceso', 'En Proceso'), ('Resolved', 'Resuelto')], default='Abierto', max_length=15, verbose_name='Estado'),
        ),
    ]
