# Generated by Django 6.0.5 on 2026-05-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_medicalevent_severity_medicalevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalevent',
            name='resolved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de resolución'),
        ),
    ]
