# Generated by Django 6.0.4 on 2026-04-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Asunto / Título')),
                ('categoria', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Salud', 'Salud'), ('Comportamiento', 'Comportamiento'), ('Suministros', 'Suministros'), ('Sistema', 'Sistema'), ('Seguridad', 'Seguridad'), ('Limpieza', 'Limpieza'), ('Otro', 'Otro')], max_length=30, verbose_name='Tipo de incidencia')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta (Urgente)'), ('Critica', 'Crítica (Atención Inmediata)')], default='Media', max_length=10)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('En Proceso', 'En Proceso'), ('Resuelta', 'Resuelta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=15)),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha_reporte', models.DateField(verbose_name='Fecha de reporte')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='animales.animal', verbose_name='Animal relacionado')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte', '-created_at'],
            },
        ),
    ]
