# Generated by Django 6.0.4 on 2026-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donante', models.CharField(help_text="Nombre del donante o 'Anónimo'", max_length=200)),
                ('donante_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('donante_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('Monetaria', 'Monetaria'), ('Material', 'Material'), ('Otra', 'Otro tipo')], max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Recibida', 'Recibida'), ('Procesada', 'Procesada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=15)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto (€)')),
                ('metodo_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque'), ('PayPal', 'PayPal'), ('Otro', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('descripcion', models.TextField(blank=True, help_text='Materiales donados, concepto del pago...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
