# Generated by Django 6.0.4 on 2026-05-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donacion',
            options={'ordering': ['-date'], 'verbose_name': 'Donación', 'verbose_name_plural': 'Donaciones'},
        ),
    ]
