# Generated by Django 6.0.4 on 2026-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='type',
            new_name='donation_type',
        ),
        migrations.AddField(
            model_name='donacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
