# Generated by Django 6.0.4 on 2026-05-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donacion',
            options={'ordering': ['-date'], 'verbose_name': 'Donación', 'verbose_name_plural': 'Donaciones'},
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='monto',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='donante_telefono',
            new_name='donante_phone',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='metodo_pago',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='estado',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='tipo',
            new_name='type',
        ),
    ]
