# Generated by Django 6.0.4 on 2026-05-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_alter_donacion_options_rename_monto_donacion_amount_and_more'),
    ]

    operations = [
    ]
