# Generated by Django 6.0.4 on 2026-05-08 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adopciones', to='animales.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adopciones', to='owners.owner')),
            ],
            options={
                'verbose_name': 'Adopción',
                'verbose_name_plural': 'Adopciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
