# Generated by Django 6.0.4 on 2026-04-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En Proceso', 'En Proceso'), ('Aprobada', 'Aprobada'), ('Completada', 'Completada'), ('Rechazada', 'Rechazada')], default='En Proceso', max_length=20)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_adopcion', models.DateField(blank=True, null=True)),
                ('adoptante_nombre', models.CharField(max_length=200, verbose_name='Nombre del adoptante')),
                ('adoptante_telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('adoptante_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adoptante_direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adopciones', to='animales.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Adopción',
                'verbose_name_plural': 'Adopciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
