# Generated by Django 6.0.4 on 2026-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
