# Generated by Django 6.0.4 on 2026-04-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopcion',
            old_name='estado',
            new_name='status',
        ),
    ]
