# Generated by Django 6.0.4 on 2026-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Coordinador', 'Coordinador'), ('Veterinario', 'Veterinario'), ('Cuidador', 'Cuidador'), ('Adiestrador', 'Adiestrador'), ('Rescatista', 'Rescatista'), ('Redes Sociales', 'Redes Sociales')], max_length=20)),
                ('info_adicional', models.TextField(blank=True, help_text='Experiencia, disponibilidad, habilidades...', verbose_name='Información adicional')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
