# Generated by Django 6.0.4 on 2026-05-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-movement_date'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='movement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_date',
            field=models.DateField(verbose_name='Fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventario.product', verbose_name='Producto principal'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad (producto principal)'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Motivo / Observaciones'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='type',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('L', 'Litros'), ('ml', 'Mililitros'), ('ud', 'Unidades'), ('caja', 'Cajas'), ('bolsa', 'Bolsas')], max_length=20, verbose_name='Unidad de medida'),
        ),
        migrations.CreateModel(
            name='MovementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Cantidad de este producto en este movimiento', verbose_name='Cantidad')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_product_set', to='inventario.movement', verbose_name='Movimiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_movement_set', to='inventario.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto en Movimiento',
                'verbose_name_plural': 'Productos en Movimiento',
                'unique_together': {('movement', 'product')},
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='movements_detail', through='inventario.MovementProduct', to='inventario.product', verbose_name='Productos del movimiento'),
        ),
    ]
