# Generated by Django 6.0.4 on 2026-05-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movement_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='products',
        ),
        migrations.DeleteModel(
            name='MovementProduct',
        ),
    ]
