# Generated by Django 6.0.4 on 2026-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Conejo', 'Conejo'), ('Hamster', 'Hamster'), ('Pajaro', 'Pájaro'), ('Otro', 'Otro')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('status', models.CharField(choices=[('En Adopcion', 'En Adopción'), ('En Acogida', 'En Acogida'), ('Adoptado', 'Adoptado'), ('Fallecido', 'Fallecido')], default='En Adopcion', max_length=20)),
                ('admission_date', models.DateField()),
                ('vaccinated', models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No'), ('Parcialmente', 'Parcialmente')], max_length=15)),
                ('spayed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['-created_at'],
            },
        ),
    ]
