# Generated by Django 6.0.4 on 2026-05-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_remove_animal_age_animal_age_months_animal_age_years_and_more'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre la relación animal-cuidador', verbose_name='Notas')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_owner_set', to='animales.animal', verbose_name='Animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_animal_set', to='owners.owner', verbose_name='Propietario/Cuidador')),
            ],
            options={
                'verbose_name': 'Relación Animal-Cuidador',
                'verbose_name_plural': 'Relaciones Animal-Cuidador',
                'unique_together': {('animal', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='animals_cuidados', through='animales.AnimalOwner', to='owners.owner', verbose_name='Cuidadores / Propietarios'),
        ),
    ]
