# Generated by Django 6.0.4 on 2026-05-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_animalowner_animal_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='owners',
        ),
        migrations.DeleteModel(
            name='AnimalOwner',
        ),
    ]
