# Generated by Django 6.0.5 on 2026-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_remove_animal_owners_delete_animalowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Tratamiento', 'En Tratamiento'), ('Sano', 'Sano'), ('Critico', 'Crítico'), ('Adoptado', 'Adoptado')], default='Disponible', max_length=20),
        ),
    ]
